apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: battleforcastile-match-consumer-deployment
  labels:
    name: battleforcastile-match-consumer
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: battleforcastile-match-consumer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: battleforcastile-match-consumer
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: battleforcastile-match-consumer
          image: "{{ .Values.image_battleforcastile_match_consumer.repository }}:{{ .Values.image_battleforcastile_match_consumer.tag }}"
          imagePullPolicy: {{ .Values.image_battleforcastile_match_consumer.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image_battleforcastile_match_consumer.container_port }}
              protocol: TCP
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: battleforcastile-match-consumer-secrets
                  key: secret_key
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: battleforcastile-match-consumer-secrets
                  key: rabbitmq_user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: battleforcastile-match-consumer-secrets
                  key: rabbitmq_password
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
